
spring:
  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分开来
    name: mysql
    # 监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
    filters: stat
    # 最大连接池数量
    maxActive: 20
    # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 1
    # 获取连接时最大等待时间，单位毫秒
    maxWait: 60000
    # 最小连接池数量
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    # 连接保持空闲而不被驱逐的最长时间
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句
    # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
    validationQuery: select count(1) from 'table'
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 是否缓存preparedStatement，即PSCache
    poolPreparedStatements: false
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
    maxOpenPreparedStatements: -1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fana?serverTimezone=Europe/London&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: Fanaroot2002
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null  #返回给前端时自动忽略null值得字段.
  redis:
    host: localhost
#    password: fanaredis
    port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#是否激活 swagger true or false
swagger:
  enable: true

logging:
  config: classpath:logback-spring-test.xml

fana:
  ip: https://file-dev.myfana.com/
  banner:
    imgPath: /app/file/images/banner/
  user:
    imagePath: /app/file/images/user/

cloudflare:
  imagePath: https://imagedelivery.net/2chPAg1PDekJ6oI478IB9Q/
  imageToken: Bearer WNpB9UIoWdv1JIded9R4EgmTDS6ylC_nyTVzXFmb
  imageUrl: https://api.cloudflare.com/client/v4/accounts/f8e81a696958a8ddce013def58fc0501/images/v1

  videoUrl: https://api.cloudflare.com/client/v4/accounts/f8e81a696958a8ddce013def58fc0501/stream
  videoToken: Bearer nbVX_nJqRuzrephOBnMJ5p-8TUuQIT3vDoNTzaMR
