server:
  port: 8881
  servlet:
    context-path: /


spring:
  profiles:
    active: dev
    #port: 端口号
    default-encoding: UTF-8
  devtools:
    remote:
      secret: fana

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #  数据库列字段xxx_r 自动映射实体类xxxR  false:关闭  true:开启
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0


